import { useAuth, useUser } from "@clerk/clerk-react";
import { useEffect, useState } from "react";
import { Heart, Users, Sparkles } from "lucide-react";
import axios from "axios";
import toast from "react-hot-toast";
import { Card } from "../components/ui/Card";
import { Badge } from "../components/ui/Badge";
import { Skeleton } from "../components/ui/Skeleton";
import { EmptyState } from "../components/ui/EmptyState";

axios.defaults.baseURL = import.meta.env.VITE_BASE_URL || "";

const Community = () => {
  const [creations, setCreations] = useState([]);
  const { user } = useUser();
  const [loading, setLoading] = useState(true);
  const { getToken } = useAuth();

  const fetchCreations = async () => {
    try {
      setLoading(true);
      const { data } = await axios.get("/api/user/get-published-creations", {
        headers: { Authorization: `Bearer ${await getToken()}` },
      });

      if (data.success) {
        setCreations(data.creations);
      } else {
        toast.error(data.message);
      }
    } catch (error) {
      toast.error(error.response?.data?.message || error.message);
    }
    setLoading(false);
  };

  const imageLikeToggle = async (id) => {
    try {
      const { data } = await axios.post(
        "/api/user/toggle-like-creation",
        { id },
        { headers: { Authorization: `Bearer ${await getToken()}` } }
      );

      if (data.success) {
        toast.success(data.message);
        await fetchCreations();
      } else {
        toast.error(data.message);
      }
    } catch (error) {
      toast.error(error.response?.data?.message || error.message);
    }
  };

  useEffect(() => {
    if (user) {
      fetchCreations();
    }
  }, [user]);

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div>
        <div className="flex items-center gap-3">
          <Badge variant="primary" className="px-3 py-1">
            Community Showcase
          </Badge>
        </div>
        <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-zinc-100 mt-2">
          Explore Public AI Creations
        </h1>
        <p className="text-sm font-medium text-slate-600 dark:text-zinc-400 mt-1">
          Discover visual artwork generated by creator community members.
        </p>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          <Skeleton className="h-64 rounded-2xl" />
          <Skeleton className="h-64 rounded-2xl" />
          <Skeleton className="h-64 rounded-2xl" />
        </div>
      ) : creations.length === 0 ? (
        <Card className="p-12">
          <EmptyState
            icon={Users}
            title="No Published Assets Yet"
            description="Be the first to publish an AI image from the Image Generator to the Community showcase!"
          />
        </Card>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {creations.map((creation, index) => (
            <Card
              key={creation.id || index}
              className="group relative overflow-hidden rounded-2xl p-2 bg-white dark:bg-zinc-900 border-slate-200 dark:border-zinc-800 transition-all duration-300 hover:shadow-xl hover:border-indigo-300 dark:hover:border-zinc-700"
            >
              <div className="relative aspect-4/3 rounded-xl overflow-hidden bg-slate-100 dark:bg-zinc-950">
                <img
                  src={creation.content}
                  alt={creation.prompt}
                  className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                />

                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 p-4 flex flex-col justify-end text-white">
                  <p className="text-xs font-semibold line-clamp-2 mb-2 text-white">
                    {creation.prompt}
                  </p>

                  <div className="flex items-center justify-between pt-2 border-t border-white/20">
                    <span className="text-[10px] uppercase font-bold tracking-wider text-zinc-300">
                      {new Date(creation.created_at).toLocaleDateString()}
                    </span>

                    <button
                      onClick={() => imageLikeToggle(creation.id)}
                      className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-white/20 hover:bg-white/30 backdrop-blur-md transition-all text-xs font-bold text-white cursor-pointer"
                    >
                      <Heart
                        className={`w-3.5 h-3.5 ${
                          creation.likes?.includes(user?.id)
                            ? "fill-red-500 text-red-500"
                            : "text-white"
                        }`}
                      />
                      <span>{creation.likes?.length || 0}</span>
                    </button>
                  </div>
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};

export default Community;

